# Generated by Django 6.0.2 on 2026-02-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_payment_intent',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_session_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='paystack_access_code',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar')], default='KES', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('paystack', 'Paystack (Card/M-Pesa)'), ('mpesa', 'M-Pesa Direct'), ('free', 'Free')], max_length=10),
        ),
    ]
