# Generated by Django 5.1.3 on 2026-02-09 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exercisesubmission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='exercise',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3, help_text='Maximum attempts allowed (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='exercisesubmission',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='exercisesubmission',
            unique_together={('student', 'exercise', 'attempt_number')},
        ),
        migrations.CreateModel(
            name='ModuleContentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=1)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_views', to='courses.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'module')},
            },
        ),
    ]
