# Generated by Django 5.1.3 on 2026-02-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_is_free_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price_kes',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price in KES for M-Pesa (0 = auto-convert from USD)', max_digits=10),
        ),
    ]
